### ISSUE TITLE
Introduce flow control between partitions

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#10087]
**Description**

Partitions send commands between each for the following cases:

- Message correlation (including correlation)
- Deployment distribution

In both cases, since communication is assumed to be unreliable, we have built-in retry mechanisms. In the event of a failure in these, or a bug on either side, it can happen that the sender overloads the receiver. Or it can be that the receiver is generally overloaded and the sender shouldn't send anything until the situation resolves itself.

There's no way for the receiver to notify the sender at the moment that it should slow down. We saw this in one incident, where the deployment distributor kept retrying deployments at a faster rate than the receiving partition could process, resulting in the build up of an incredibly large log and that partition being effectively unavailable from a user point of view.

Ideally, we should see a solution which satisfies the following:

- [ ] Commands from other partitions can be rejected based on the current load, sharing the same rate limiter as external commands
- [ ] Certain commands may need to be whitelisted (e.g. backup/checkpoint related commands)
- [ ] The receiving partition can provide information about when to retry
- [ ] The sending partition does not buffer commands for retry in an unbounded way

The last point is to ensure we don't run out of memory by buffering commands to be sent to a given partition which is unable to process any commands for a longer period of time.

**Comment by menski** [comment]
Probably a M size issue (up to 6 weeks), and it is not urgent if not something else goes wrong. We should look at it as an improvement for next quarter, and evaluate if there is any overlap with other initiatives around inter-partitions communication, i.e. switching to gRPC.

**Comment by megglos** [comment]
affected partition stability in an incident https://app.incident.io/camunda/incidents/599
2 partitions got overloaded with message subscription create commands and the backlog was growing at a higher rate than the processing

**Comment by npepinpe** [comment]
Planning:

- Time box 8 hours to propose a solution/breakdown for this

@oleschoenburg and @deepthidevaki will look into it in the next two weeks

**Comment by oleschoenburg** [comment]
@deepthidevaki and I looked into this a bit from the angle of "let's improve flow control in general". In particular, https://github.com/camunda/zeebe/issues/14316 was at the back of our minds.

We think that a first step in the right direction would be to remove the `LogStorageAppender` in general and replace it with a simple limiter that sits in front of the `Sequencer` to protect the raft thread from overloading it with too many writes. We think that a fixed limit or a simple RTT based limit would work well for this.

As a second step, we can move the flow control for user commands away from the `CommandApi` and implement it in front of the `Sequencer` instead. The idea here is to have one common place where flow control for commands is implemented. User commands would then acquire permits from two limiters, the configured one for user commands (AIMD by default), and the raft thread limiter.
To implement this, I propose a new class that sits in front of the `Sequencer`. The `Mixer` would decide which flow control to use, based on the _source_ of records. Sources would be _User Commands_, _Processing Results_, _Internal Commands_ and _Remote Commands_. 

**After implementing the first two steps, the system behavior should remain almost the same**. User commands go through a configurable limit while other records such as processing results, internal commands (e.g. timer triggers), and remote commands (e.g. message correlation) are only held back by the limiter that protects the raft thread.

Building on top of this, we can think about adding flow control for _Remote Commands_. The challenge here is that we probably can't just drop commands silently. Let's take message correlation as an example: When a _Correlate_ command is sent to a remote partition, the sent time is updated immediately and the correlation is only attempted again after 10 seconds. If we were to introduce a limiter for remote commands, we might run into problems because every dropped command will result in at least 10 seconds of delay. Ultimately, a solution similar to https://github.com/camunda/zeebe/issues/13870 would be desirable. The difference here is that we must wait for the command to be received, written _and committed_ on the remote partition. Currently, this is not possible because inter-partition communication is a one-way channel from sender to receiver.
Instead, we can extend the inter-partition command sender to take a completion callback that is executed whenever the command is written on the remote partition. We can then use that for message correlation (and possibly other performance sensitive features such as signals) to shorten the retry interval for messages that were not written on the receiver.


```[tasklist]
## Refactoring flow control
- [ ] Let the `Sequencer` write directly to the raft thread
- [ ] Implement a `Mixer` component in front of the `Sequencer` 
- [ ] The `Mixer` protects the raft thread from overloading
- [ ] The `Mixer` provides metrics for flow control state
- [ ] Record writers are categorized by use-case
- [ ] The `Mixer` applies flow control for user commands
- [ ] Cleanup: Building a `LogStreamWriter` should not be async
```

**Comment by deepthidevaki** [comment]
A prequel to Ole's comment above.

We prototyped flow control in Sequencer. We added separate request limiters  for user commands, remote commands and internal commands. Processing result from stream processor is never rejected. All limiters are configured to use AIMD. Limiters for internal and remote commands are configured to be more lenient to ensure internal backlog can make progress even if there is high load from users, but this is up for discussion.

Although our main goal is to limit remote commands, we first evaluated with a high load of timers because it was the easiest to setup a benchmark with timers. **Result: The cluster with the limiters for internal-commands is still running strong after a couple of days. The reference benchmark is almost dead now with 400Mil of processing queue size.** 

Reference
![image](https://github.com/camunda/zeebe/assets/1997478/5e211b1c-5bcc-4278-9e8d-44c8abbea0ce)

POC with flow control for user, remote and internal commands.
![image](https://github.com/camunda/zeebe/assets/1997478/d9873bfa-5e27-42d7-b8d7-57e3478261d6)

Next question is how this type of flow control works for remote commands. As Ole explained before, rejecting remote commands can cause higher delay in message correlation mainly because we are not retrying aggressively enough. In a very high load, similar to what we saw in the support incident, it is probably fine. But in a normal load scenario we have to ensure that the messages are still correlated in real-time. We have not evaluated this yet. So as a next step, I would like to evaluate the impact of flow control for remote commands. Based on the results, we can decide whether we want to add request limiters for remote commands in the Sequencer (together with better retry strategy on the sender) or add caching similar to the timers proposed for #13870 or a combination of both. 

Nevertheless, we should take the next steps proposed by Ole above.

**Comment by Zelldon** [comment]
@deepthidevaki just want to mention that we already implemented caching for the writes in https://github.com/camunda/zeebe/pull/15073

**Comment by deepthidevaki** [comment]
Ya. I know. Only for internal commands, right?

**Comment by npepinpe** [comment]
I think caching for remote commands is gonna be really tricky. I suppose you could do it on the receiver side :thinking: That would reduce a bit the load on the remote commands for back pressure I guess.

**Comment by deepthidevaki** [comment]
> I think caching for remote commands is gonna be really tricky. 

True. We don't have a prototype for it yet.

We discussed the following for backpressure approach
1. Buffering in the receiver and receiver can retry (limit the number of retries) if the write was rejected due to backpressure. This can put more pressure on receiver which might be already overloaded.
2. Buffering in the Inter-partition sender and retry if the write was rejected due to backpressure. (limit the number of retries). The record is already buffered in the engine, but we have to buffer it again in inter-partition sender.
3. Somehow the recurrent checkers in engine should know to retry faster if it was rejected due to backpressure. Needs more information exchange between the inter-partition transport and the checkers.

1 and 2 is in the direction of providing more reliable transport for inter-partition.

Alternate is to follow the caching approach used for timers, to reduce the chance of backpressure due to sender repeatedly trying to send the same commands. But here the most tricky is that the we can mark it as written only when the receiver has written and committed the command. Also how to handle if the command was rejected -> should retry again?

Adding backpressure will be the easiest part to implement, but the problem is that in specific workloads there is a chance that a few messages get delayed forever because they were unlucky and get caught in the backpressure loop.

**Comment by deepthidevaki** [comment]
It was unclear to me before whether we want to add flow control for internal commands now that we have the caching solution. It seems caching did not fully solve [the problem encountered by a user](https://github.com/camunda/zeebe/issues/13870#issuecomment-1806793306). Flow control for internal commands would likely solve the reported issue.

So I'm putting this issue back to inbox to discuss it in next traige/planning. It would make sense to start implementing the changes proposed [in the above comment](https://github.com/camunda/zeebe/issues/10087#issuecomment-1802371153) even if we don't have a completed solution for IPC.

**Comment by megglos** [comment]
@deepthidevaki can you link the prototype PR/branch here? thanks!

**Comment by deepthidevaki** [comment]
Branch with POC https://github.com/camunda/zeebe/tree/os/unified-flow-control

**Comment by dddpaul** [comment]
Hi.

I've tested this case https://github.com/camunda/zeebe/issues/13870#issuecomment-1806793306. Seems like queue size is really capped now (was up to 1mil events, now up to 500k events). But this the only good news. Overall performance became lower, windows of unavailability became wider. It's reasonable, because number of timer events doesn't change it's just processed slower now.

![image](https://github.com/camunda/zeebe/assets/628226/f77e316d-2a8b-4ab5-9302-1595db56673e)

I've expected that with limited processing of timer events - there will be some "bandwidth" for processing new events (create new PIs). That' doesn't happen.

**Comment by deepthidevaki** [comment]
> I've expected that with limited processing of timer events - there will be some spare "bandwidth" for processing new events (new PIs). That doesn't happen. Why?

This could be because in the poc, we deliberately configured flow control for user commands and internal commands differently. We are more aggressively rejecting user commands while accepting more internal commands.

**Comment by npepinpe** [comment]
I think this is mostly satisfied with #17547.
