### ISSUE TITLE
Duplicate Process Instances

### ISSUE THREAD

**Issue by NingyuanZhang** [camunda/camunda#27689]
**Describe the bug**

We sent a grpc request to zeebe to create a new process instance, but 2 process instances were created with exactly same variables
Timeline:
Jan 31, 2025 16:52:36.254 new process instance 1 created on partition 12, processInstanceKey 27021597776970650
Jan 31, 2025 16:52:38.785  new process instance 2 created on partition 10, processInstanceKey 22517998149640107
between the above two timestamps, one broker of partition 10 was failed and restarted, leader was transitioned as well. Will it cause duplicate instances created? 

**To Reproduce**

It is hard to reproduce. We sent a batch of requests, only this one has duplicate, which seems random. 

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.4.5
- Configuration:

**Comment by korthout** [comment]
@npepinpe The CreateProcessInstance RPC uses `sendRequestWithRetryPartitions` which does a retry which internally checks `shouldRetryWithNextPartition` on specific errors. This includes partition leader mismatch. Do you think that could lead to this issue?

https://github.com/camunda/camunda/blob/3b39dc74977cc7e334a9907b0663619feb54a0bb/zeebe/gateway-grpc/src/main/java/io/camunda/zeebe/gateway/EndpointManager.java#L217-L225

https://github.com/camunda/camunda/blob/3b39dc74977cc7e334a9907b0663619feb54a0bb/zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/broker/RequestRetryHandler.java#L143-L151

**Comment by npepinpe** [comment]
Barring a bug, it shouldn't not create two process instances on leader mismatch, assuming that's the error that was returned.

Do we retry on timeout? That's the only case where I could see this happening (again, barring any bugs).

**Comment by megglos** [comment]
Chiming in here 8.4.5 was affected by https://github.com/camunda/camunda/issues/17333 which got fixed in 8.4.7. @NingyuanZhang could you try whether you can reproduce this with 8.4.7 or newer?

**Comment by korthout** [comment]
Looking at this again together with @mustafadagher and we noticed the `ConnectException`. That's probably wrong, because what could be reasons for a connect exception? If it includes network failure on the response, then it's possible that the command was accepted and processed on one partition and then still gets retried. This should not happen because create instance is not idempotent.

https://github.com/camunda/camunda/blob/3b39dc74977cc7e334a9907b0663619feb54a0bb/zeebe/gateway/src/main/java/io/camunda/zeebe/gateway/impl/broker/RequestRetryHandler.java#L143-L151

We noted this during exploring #46722.

---

EDIT: Looking at https://github.com/camunda/camunda/pull/18264, it appears that this removed several cases where a ConnectException is thrown. But did this cover all cases? To be safe, I think we should just remove the ConnectException retry for non-idempotent requests altogether.

**Comment by marcosgvieira** [comment]
### 🧭 Triage Assessment

| Field | Value |
|------|-------|
| **Work type** | BUG |
| **Severity** | 🔥 High |
| **Likelihood** | ℹ️ Low |
| **Confidence** | 0.8 |

---

### 📝 Rationale

Creating duplicate process instances from a single createProcessInstance request in Zeebe 8.4.5 is incorrect runtime behavior in a released version and can significantly impact production workflows, but it appears to occur only under rare leader/network failure conditions and has at least partial mitigation in newer versions.

---

🤖 _This issue was automatically triaged by an AI-based system as part of the Core Features triage workflow._

✋ **Want a human review?**
If you believe this assessment is incorrect or needs adjustment, feel free to update the details or request a manual triage by adding the **`triage:manual`** label.

**Comment by megglos** [comment]
@korthout as of https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/net/ConnectException.html should only occur if a connection could not be established, so it should be save to retry if not thrown falsely like it was the case before. did we had any recent observations of the issue on a newer release since https://github.com/camunda/camunda/issues/17333 got fixed?

I'll close this as the report was on a version that was affected by the bug.
