### ISSUE TITLE
Batch Operation in Operate Doesn't Apply to All Selected Processes

### ISSUE THREAD

**Issue by ArezooAzar** [camunda/camunda#34610]
### 

### 

### 

### 

### Description

When performing a batch operation (e.g., retry) on multiple processes in Camunda Operate, the operation is only applied to the number of processes currently visible in the list, rather than all selected processes in the full view.

### Steps to reproduce

1. Open Operate.
2. Ensure there are more than 50 process instances (test data with a large dataset is recommended).
3. Use the checkbox to "Select All" from the process list.
4. Apply a batch operation such as Retry.
5. Observe the Operation Panel.

### Current behavior

The number of processes shown in the Operation Panel does not match the total number of selected processes in the process list. It appears to only apply to visible items, not all selected items in the full filtered view

### Expected behavior

The batch operation should be applied to all selected processes, not just those visible on the current page. The Operation Panel should reflect the total number of processes selected from the list.

### Environment

SaaS

### Version

- Component Version: [e.g. 2.0.0]

### Dev -> QA handover

- Resources:
- Versions to validate:
- Release version (in which version this feature will be released):

### Links

https://github.com/user-attachments/assets/59f95fac-dd3a-49ac-9479-41b9e20e955b

**Comment by juliasaienko** [comment]
@ArezooAzar Could you please take another look at this? The API has been migrated, and I was able to successfully perform the retry operation on more than 50 elements during local testing.

<img width="472" height="119" alt="Image" src="https://github.com/user-attachments/assets/998a1cc0-25bc-4d11-96d8-8a3df13cdb37" />

**Comment by ArezooAzar** [comment]
@juliasaienko :
I tested this in SaaS version 8.8.0-alpha8, but it’s not working. In fact, not only the retry function, but also the cancel function isn’t behaving as expected.
It doesn’t matter whether I select all processes or just some—only one or two of them are actually executed.

[here is the cluster](https://chaos-1.operate.ultrawombat.com/6020c242-4b1c-4015-91cf-f94f124d59a8/operate/processes?incidents=true) if you want to try 

https://github.com/user-attachments/assets/ad957529-6f7e-4858-bf89-75cc37d8ed5e

**Comment by pedesen** [comment]
@ArezooAzar We did some root-causing, here's what we found so far:

- There are no details visible in the operations panel, because the operations are in "PARTIALLY_COMPLETED" state. This will be fixed with https://github.com/camunda/camunda/issues/37365
- All operations are failing because of an error:
```
Failed to initialize batch operation with end cursor: null. Reason: Cannot invoke
"io.camunda.search.clients.SearchClientsProxy.withSecurityContext(io.camunda.security.auth.SecurityContext)\" because 
"this.searchClientsProxy\" is null
```
we're currently root-causing why this happens

**Comment by mustafadagher** [comment]
This issue is not reproducible locally.
However, the error here shows that the `searchClientsProxy` is `null`. The `searchClientsProxy` is injected to the `BrokerModuleConfiguration` in the `dist` module, and is not required for start-up.
https://github.com/camunda/camunda/blob/9c5e103c35d456901a67df688f6d1fe1068119ff/dist/src/main/java/io/camunda/zeebe/broker/BrokerModuleConfiguration.java#L81

There two different beans that could be injected as implementation for `searchClientsProxy`
- `CamundaSearchClients`: https://github.com/camunda/camunda/blob/9c5e103c35d456901a67df688f6d1fe1068119ff/dist/src/main/java/io/camunda/application/commons/search/SearchClientDatabaseConfiguration.java#L92-L101
- `NoDBSearchClientsProxy`: https://github.com/camunda/camunda/blob/9c5e103c35d456901a67df688f6d1fe1068119ff/dist/src/main/java/io/camunda/application/commons/search/SearchClientDatabaseConfiguration.java#L80-L84

Both are dependent on whether `secondaryStorage` is enabled or disabled. It's enabled and is set to `elasticsearch` by default in `ConditionalOnSecondaryStorageEnabled`

**Yet, the whole configuration class (`SearchClientDatabaseConfiguration`) is `ConditionalOnRestGatewayEnabled`.**

The implementation of `ConditionalOnRestGatewayEnabled` is dependent on two  properties (`zeebe.broker.gateway.enable`, `camunda.rest.enabled`) as follows:
https://github.com/camunda/camunda/blob/9c5e103c35d456901a67df688f6d1fe1068119ff/zeebe/gateway-rest/src/main/java/io/camunda/zeebe/gateway/rest/ConditionalOnRestGatewayEnabled.java#L23-L31

💭 ❓ So, my guess, that we would need to confirm, is that those properties might have changed recently on `8.8-alpha8`? probably due to the new unified configs? 

CC: @tmetzke 
also @deepthidevaki if you are aware if such change, it could shorten the investigation 😄

**Comment by deepthidevaki** [comment]
> also @deepthidevaki if you are aware if such change, it could shorten the investigation

Those properties are modified yet, as far as I know. I don't see it mentioned in [here](https://docs.google.com/spreadsheets/d/1R4epsy6DWemA8_76cUE6zOGUFbrXCXlM2reXnKFuz7Y/edit?gid=818158292#gid=818158292) and I don't see any code related to it in the unified config.

**Comment by mustafadagher** [comment]
💡 With [help](https://camunda.slack.com/archives/C08F5RD5X8B/p1757604919752439?thread_ts=1757603587.557329&cid=C08F5RD5X8B) from @houssain-barouni , I figured out that the test cluster have `a standalone gateway` and no `embedded gateway`. 

As per the configurations mentioned above `ConditionalOnRestGatewayEnabled`, when no embedded gateway is configured, the search client bean won't be configured.

I'll remove this dependency to create readers and search clients only when embedded gateway exists, since we need them for the broker anyway to be able to query batch operations items.

**Comment by ArezooAzar** [comment]
@mustafadagher: I noticed you marked this issue as complete. Could you please let me know which version I can test the fix in?
I tried using the [Snapshot](https://console.cloud.ultrawombat.com/org/6ff582aa-a62e-4a28-aac7-4d2224d8c58a/cluster/32aa08b0-c662-4894-b133-4e096fac1cf1) version, but I still see the issue.

**Comment by mustafadagher** [comment]
Hi @ArezooAzar , I've [merged the fix to `stable/8.8`](https://github.com/camunda/camunda/commit/529515157bf3f63c572044496b491eebe1d7343a) on `Sept. 12 @ 4:34PM CEST`.

I'm not educated on the deployment process and not sure how and when we build the SNAPSHOT versions to be deployed to `saas-int`, but if we are sure this commit is there and it does not work, please let me know.

Just a hint, I didn't resolve the UI issue, that will be separately addressed by @pedesen and @juliasaienko , I fixed the underlying BE issue.

**Comment by mschoe** [comment]
@ArezooAzar, the stable/8.8 branch builds its own SNAPSHOT called **Camunda 8.8.0 SNAPSHOT**

**Comment by ArezooAzar** [comment]
@mustafadagher : I checked on the Snapshot version, and it still does not work there. Send error ( Partially completed⚠️ )
[here is the cluster](https://hel-1.operate.ultrawombat.com/4bed83a2-b638-4fd1-9b63-40af396d4a15/operate/processes?active=true&incidents=true) if you want to check

**Comment by mustafadagher** [comment]
@ArezooAzar yes, it's not fixed yet. 
As reported on [slack](https://camunda.slack.com/archives/C088A1LL5CZ/p1758025242853729?thread_ts=1757486110.014909&cid=C088A1LL5CZ), I found another error (tracked in a separate issue https://github.com/camunda/camunda/issues/38214) and I'm working to fix it in https://github.com/camunda/camunda/pull/38225. I'll let you know once the new fix is backported to `stable/8.8`

**Comment by mustafadagher** [comment]
@ArezooAzar after merging the fix from #38214 to `stable/8.8`, I was able to verify this now works as expected on a `Camunda 8.8-SNAPSHOT` cluster.

<img width="1701" height="678" alt="Image" src="https://github.com/user-attachments/assets/29218dcd-c85d-4e93-b442-b141a4204d2b" />

**Comment by mschoe** [comment]
@ArezooAzar, could you please have a second look at the fix and close the issue once testing has been done?

**Comment by ArezooAzar** [comment]
@mustafadagher  : I tested and noticed two issues:

1. There are 390 instances in the process instance list. When I select all, it correctly says, **selected 390.** But when I click on **retry**, it randomly shows a different number of retried instances, like 60, 130, or 260 instead.
2. It also always shows only **one operation ID**; I’m not sure what that refers to.
3. When I click that operation, it points to just one specific process ,  in this case, flight registration.
4. Additionally, t**he progress bar doesn’t disappear after a few attempts**.

All these issues can be seen in the attached screen recording.
[Here is the cluster](https://hel-1.operate.ultrawombat.com/15bda121-62d4-401d-a482-b28b6be2fbce/operate/processes?active=true&incidents=true&completed=true&canceled=true&operationId=6755399441058759) 

https://github.com/user-attachments/assets/2bf549a7-7521-42a8-9fe1-1dc47f3aeb14

**Comment by pedesen** [comment]
Hey @ArezooAzar 

> 1. There are 390 instances in the process instance list. When I select all, it correctly says, selected 390. But when I click on retry, it randomly shows a different number of retried instances, like 60, 130, or 260 instead.

It's expected that only instances with incidents are retried. You also selected instances without any incident, these will just be ignored. That's the reason the count might be different.

> 2. It also always shows only one operation ID; I’m not sure what that refers to.

Can you explain this a bit more please?

> 3. When I click that operation, it points to just one specific process , in this case, flight registration.

This is also related to my answer of 1. Apparently flight registration is the only process definition which has instances with incident in the selection. Again, instance without incidents are not retried.

> 4. Additionally, the progress bar doesn’t disappear after a few attempts.

This should not be the case. The progress bar should disappear as soon as the operation from the API response has an end date. Could you please share the API response from the network tab, so we can check what's happening? Thanks

**Comment by ArezooAzar** [comment]
@pedesen : thanks for the clarifications 

Would you like me to create an issue for the last one (the progress bar is not disappearing)?

**Comment by pedesen** [comment]
@ArezooAzar That would be great, thanks!

**Comment by ArezooAzar** [comment]
> [@ArezooAzar](https://github.com/ArezooAzar) That would be great, thanks!

done ✅  [here is](https://github.com/camunda/camunda/issues/38518) the issue

**Comment by mustafadagher** [comment]
@ArezooAzar is this done now? can we close this issue?
